# Drupal 8 recipe
name: core8

# Start with the default Drupal 8 recipe
recipe: drupal8

# Configure the Drupal8 recipe
config:
  php: '7.2'
  via: nginx
  webroot: web
  xdebug: true
  conf:
    php: config/php/php.ini

services:
  appserver:
    run:
      - composer install

  database:
    type: mariadb

# Mailhog things
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward: true

proxy:
  mailhog:
    - mail.core8.lndo.site
